### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by 3052** [az0mb13/frida_setup#2]
I am currently using Android Studio with MITM Proxy - is this able to work with that?

**Comment by az0mb13** [comment]
You might have to pass some extra flags like `-writable-system` when booting up your Android emulator because by default it won't allow you to have a writable system. 
It should work. Just try to run each command individually and fix any errors. That above flag fixed most of it last time I remember. 
Also, I didn't try with MITM proxy. This script gets a certificate from your Burp's listener so you might need to update that according to your config. 

```
./emulator -avd <your_avd_name> -writable-system
```
